### ISSUE TITLE
サムネイルのサイズをOGPサイズにする

### ISSUE THREAD

**Issue by nztm** [Mekurun/mekurun.com#130]
- [x] コンテンツのサムネイルサイズを1200 * 630にする

- [x] それをOGPにする設定も加えてもいいかもしれない(ない場合はデフォルト)

**Comment by nztm** [comment]
@yuki384 これってもうできてたっけ。

**Comment by yuki384** [comment]
まだできてない💦
これは、一覧でみたときのサムネイルの比率を `1200 * 630` と同じ比率に合わせる、という話だよね？

**Comment by nztm** [comment]
そうね、それも含まれるかな。
今は16:9に無理やり合わせてる感じ？

**Comment by yuki384** [comment]
> 今は16:9に無理やり合わせてる感じ？
比率調整は何もやってない認識だよ！

**Comment by nztm** [comment]
なるほど、まあまたお願いしたいー！

**Comment by yuki384** [comment]
この2つのコミットで対応しました✅
https://github.com/Mekurun/mekurun.com/commit/0b3cfaa7353d528b8648a1fb4442131312660705
https://github.com/Mekurun/mekurun.com/commit/dfaff44525abc4218b0f14c3b074528ac8e46b2d
