### ISSUE TITLE
大きなディスプレイで見た時にサムネイル画像がぼやける

### ISSUE THREAD

**Issue by nztm** [Mekurun/mekurun.com#131]
画像だとわかりにくいかもだけど、FullHDのディスプレイで見ると
結構ぼやけていたので、Cloudinaryのwidth設定を改める必要がありそう

![2020-06-28_214504](https://user-images.githubusercontent.com/43288418/85949332-19a71c00-b991-11ea-8c21-04310fb947b4.png)

**Comment by yuki384** [comment]
https://github.com/Mekurun/mekurun.com/commit/05e88c78a7b347bea831717a1ae83a9e0b4caafc で対応しました。ページのコンテンツの最大幅も決めたので、このような表示になります🔽
![image](https://user-images.githubusercontent.com/31533303/86788139-cb84cd80-c0a0-11ea-994d-7d5cab0a3234.png)

**Comment by yuki384** [comment]
コンテンツの最大幅を1200pxに変更したのでこうなります
![image](https://user-images.githubusercontent.com/31533303/86789716-90839980-c0a2-11ea-86d3-e93d0b6849ea.png)
