### ISSUE TITLE
横幅の大きいディスプレイで見たときにコースを見るの位置がおかしい

### ISSUE THREAD

**Issue by nztm** [Mekurun/mekurun.com#136]
- コースをみる の位置を右側に固定したほうがいいかもしれない。

## スクリーンショット / Screenshot

![コメント 2020-06-30 135904](https://user-images.githubusercontent.com/43288418/86085403-05bb0180-bada-11ea-86c3-f793af27b3fd.png)

**Comment by yuki384** [comment]
https://github.com/Mekurun/mekurun.com/commit/c5674c28ab705155d972c17d9e7fa83b3d8fe2a3 で解決したので確認後closeお願いします〜

**Comment by nztm** [comment]
確認しました！ありがとう！
