### ISSUE TITLE
フォントによってボタンとかで文字が中央のラインからずれている

### ISSUE THREAD

**Issue by nztm** [Mekurun/mekurun.com#143]

**Comment by nztm** [comment]
macOS Chrome 83 フォント不明
<img width="859" alt="スクリーンショット 2020-07-02 13 49 52" src="https://user-images.githubusercontent.com/43288418/86317893-85c4a100-bc6b-11ea-96b6-7eb190da472d.png">

**Comment by nztm** [comment]
Windows 10 Chrome 83 Meiryo
Meiryo UIが適用されている「PDFで見るボタン」は中央ラインに揃っている
![コメント 2020-07-02 135547](https://user-images.githubusercontent.com/43288418/86317997-c6bcb580-bc6b-11ea-81bc-701b2b7b25f6.png)

**Comment by yuki384** [comment]
https://github.com/Mekurun/mekurun.com/commit/91e386264d8374497db13d2dfc25e9a57648846d で治ったはずです！確認後問題なければcloseお願いします〜
