### ISSUE TITLE
記事一覧ページのデザインの改善

### ISSUE THREAD

**Issue by nztm** [Mekurun/mekurun.com#144]
ページの説明はメインビジュアルのタイトルの下に小さく入れたほうがよいかも。
他のデザインに関しては裁量に任せます。

#67 の実装はとりあえず後からでもよい

みんなの作品に関してはゲーム系、物語系など、わけて今後表示してリリースしたいので、
とりあえずは、他のページと合わせておいてもらえると。

<img width="1322" alt="スクリーンショット 2020-07-02 14 00 32" src="https://user-images.githubusercontent.com/43288418/86318477-fae4a600-bc6c-11ea-9d63-efe796408ef0.png">

<img width="1320" alt="スクリーンショット 2020-07-02 14 02 42" src="https://user-images.githubusercontent.com/43288418/86318481-ff10c380-bc6c-11ea-9ff6-bb8baba6c371.png">

<img width="1324" alt="スクリーンショット 2020-07-02 14 02 29" src="https://user-images.githubusercontent.com/43288418/86318480-fe782d00-bc6c-11ea-9322-9ee2cd010fa3.png">

**Comment by yuki384** [comment]
https://github.com/Mekurun/mekurun.com/commit/154566ce71335af3c2d80cfa6d013976aefc539a ✅
