### ISSUE TITLE
コースのコレクションごとにフォルダ分けする

### ISSUE THREAD

**Issue by nztm** [Mekurun/mekurun.com#150]
コースごとにMarkdownのフォルダ分けをする

_course/ja/course名
👉 _course/ja/scratch/course名
👉  _course/ja/minecraft/course名

**Comment by yuki384** [comment]
https://github.com/Mekurun/mekurun.com/commit/e8bef6cb7c22f2c7e2cfa4a59c76c2ba1d64a508 ✅
