### ISSUE TITLE
コースページにトップに戻るボタンを設置するか検討する

### ISSUE THREAD

**Issue by nztm** [Mekurun/mekurun.com#165]
デザインの段階にあった「トップに戻るボタン」の実装を検討する

<img width="741" alt="スクリーンショット 2020-07-13 14 24 31" src="https://user-images.githubusercontent.com/43288418/87273636-a1099900-c514-11ea-94b1-65eb81fb6cfe.png">

**Comment by yuki384** [comment]
「Scratch>むずかしい」を「トップにもどる/コース一覧に戻る」などにするのもありかも？
