### ISSUE TITLE
Google Tag Managerのデータ計測の設定

### ISSUE THREAD

**Issue by nztm** [Mekurun/mekurun.com#171]
## サイト全体
- [x] FooterのFB、GitHub、Twitterのクリック数計測

## 記事ページ
-  ~~読了率をスクロール率で計測~~ →アナリティクスの滞在率

## コレクションページ
- ~~コースのクリック数計測~~

## スライドページ
- ~~スライドページのアクティブユーザを計測(方法: タイマー)~~ →アナリティクスの滞在率
- [ ] スライドを何ページまで見たか計測 or 何%見たか →どうやる？
- [x] PDFの閲覧数を記録

**Comment by yuki384** [comment]
- スライド内の離脱したページを見たいかも
- シェアボタンのクリック数もあとでとる
- Search Console完了！

**Comment by yuki384** [comment]
YouTubeの進捗率はかれるんだ！

**Comment by yuki384** [comment]
YouTube Done
