### ISSUE TITLE
コースのPDFをダウンロードできるページをつくる

### ISSUE THREAD

**Issue by nztm** [Mekurun/mekurun.com#202]
今はそれぞれのコースページに行かないとPDFがダウンロードできないので、
コース一覧ページのようなものをつくってそこからPDFをダウンロードできるようにしたい。

**Comment by yuki384** [comment]
2種類の表示を思いついた by nztm
- リスト表示(お知らせ)
- カード表示(コレクションページ風)

**Comment by yuki384** [comment]
コース一覧ページにする。その中でPDFもダウンローできる形に。

**Comment by yuki384** [comment]
yuki384がUI案つくるよ
