### ISSUE TITLE
コースページのコンテンツを再検討する

### ISSUE THREAD

**Issue by nztm** [Mekurun/mekurun.com#225]
コースページのボタンを再検討したい。

「難易度」のボタン 👉 「トップに戻る(コース一覧に戻る)」
今の難易度表示はクリックできる要素なのか押さないとわからない。
トップに戻るボタンなどにしたほうが外部から直接コースにアクセスした人もわかりやすい。

スライドの難易度をサイト掲載版は消しているが、これを表示するようにすれば問題なさそう。

「PDFで見る」👉 「サンプルを見る」
PDFをDLできるページが用意できたら、ScratchのサンプルPJに飛ぶようにしても良いかも。

**Comment by yuki384** [comment]
> 「難易度」のボタン 👉 「トップに戻る(コース一覧に戻る)」
今の難易度表示はクリックできる要素なのか押さないとわからない。
トップに戻るボタンなどにしたほうが外部から直接コースにアクセスした人もわかりやすい。
スライドの難易度をサイト掲載版は消しているが、これを表示するようにすれば問題なさそう。

https://github.com/Mekurun/mekurun.com/issues/165 で考える💭
