### ISSUE TITLE
かなモードの切り替えのスイッチをボタンにする

### ISSUE THREAD

**Issue by nztm** [Mekurun/mekurun.com#242]
## なにを実装・改善したいのか

かなモードの切り替えのスイッチをボタンにする

## なぜ実装・改善したいのか

- スイッチだと挙動が変
- 子どもたちがスイッチだとわかりにく
- ちょっと小さいからもっとデザインを合わせたい

## どのように実装・改善したいのか (任意)

Progateの「無料お試しを始める」みたいなにボタンにするといいかも。
https://prog-8.com/business
<img width="1680" alt="スクリーンショット 2020-08-24 23 27 56" src="https://user-images.githubusercontent.com/43288418/91057071-b7e9f200-e661-11ea-95db-4c63d9ae5c5f.png">

## Issueのクローズに必要なこと

- [ ] ボタンの変更
- [ ] スマホデザインも含めた改善

**Comment by yuki384** [comment]
対応済み with https://github.com/Mekurun/mekurun.com/commit/6edef1b25e3545853564b2d8f69e061ddd386dbb
