### ISSUE TITLE
404時のトップに戻るボタンにひらがなも追加する

### ISSUE THREAD

**Issue by T-taku** [Mekurun/mekurun.com#248]
## なにを実装・改善したいのか
404ページが表示されるときに、「トップに戻る/Go to back」というボタンがありますが、ひらがな表記がないため、ひらがな表記を追加したい。

## なぜ実装・改善したいのか
一人で学んでいる小学生や、小さい子には漢字が少し難しい気がしました。(また、CoderDojoで使うなら、なおさら一人で使う機会があると思います。)

## どのように実装・改善したいのか (任意)
ボタンの表記に、ひらがな表記を追加する。

## いつまでに行うべきか (任意)

できるだけ早めがおすすめです。

## Issueのクローズに必要なこと

- [ ] ボタンにひらがな表記を追加する
- [ ] サーバーに反映
- [ ] 完了

## 関連Issue

なし

**Comment by yuki384** [comment]
issueの作成ありがとうございます！漢字が苦手な方にわかりやすい表記を用意するのは大事ですね (≧∇≦)b✨

**Comment by yuki384** [comment]
https://github.com/Mekurun/mekurun.com/commit/f7494627e1bd07c021aed4f07a8cff989bea03ae で対応しました✅
後ほど別途本番環境にマージしますが、開発環境での最新のコードに反映されたのでcloseします(≧∇≦)b
ありがとうございましたm(_ _)m

**Comment by T-taku** [comment]
おつかれさまです👍
