### ISSUE TITLE
スライドページのデザイン改善

### ISSUE THREAD

**Issue by yuki384** [Mekurun/mekurun.com#8]
- [x] レッスンページの戻る・進むボタンをプログレスバーの直下に固定 https://github.com/nztm/mekurun/commit/d05a02fc50f88af6bb722159a0d753838faddd86
- [x] プログレスバーの横幅をマックスにする https://github.com/nztm/mekurun/commit/5fc9a5dbf7c37cca5976ecfccc7e2d8b28d067bf
- [x] プログレスバーの位置固定 https://github.com/nztm/mekurun/commit/36927ee1acb207b9525080e04e04f6d59a66f3b2
- [ ] 画面に縦幅と横幅をできるだけあわせて、最大表示にする

**Comment by yuki384** [comment]
「 画面に縦幅と横幅をできるだけあわせて、最大表示にする 」は解像度の問題も考えると無理にしなくて良さそう。
> PCでみた時に難易度表示のmargin topがないので、とってほしい。

完了。

> トップページに戻るボタンがあったけど、どうする？

別issueで考えましょ

> パンくずリストに習って、難易度表示の>もFontAwesomeにしてもよいかも。

nztm対応ありがとう〜

> 👇ボタンがあってもいいかもね

別issueで！


こちら一旦閉じても良いかしら？

**Comment by nztm** [comment]
うーん、margin-top 24pxぐらいでもいいかも。
まだ狭い感じがする。

HTMLのスタイルタグでmargin調整してるのはなにか意図があるの？
style="margin-top:12px;

> トップページに戻るボタンがあったけど、どうする？
これはあったほうがいいかも？
ブラウザの戻るボタンを知らない子はコース終わった後に戻りたいけど、どこ押せばいいか分からなくなるような。

> 👇ボタンがあってもいいかもね
サブコースを1つでも追加するならその時までには必要
別Issueにしてもいいけど、結局はやめには変わりないかも..

**Comment by nztm** [comment]
margin-top 24pxだとPC版はいい感じだけど、
モバイル幅は余白ありすぎなのか...うーん。。

**Comment by yuki384** [comment]
> うーん、margin-top 24pxぐらいでもいいかも。

これはボタンと言うよりはヘッダーと考えてもらうとわかりやすいと思います。GitHubのヘッダーもコンテンツを邪魔しないようなコンパクトな高さになっていますね
![image](https://user-images.githubusercontent.com/31533303/87239642-69371e80-c44c-11ea-9c2d-f4063b6fdcb2.png)


> HTMLのスタイルタグでmargin調整してるのはなにか意図があるの？

これは、classを新しくつくる面倒さから直接指定してしまいました…

> 別Issueにしてもいいけど、結局はやめには変わりないかも..

僕の作業のやりやすさが変わるので分けますね〜。

**Comment by nztm** [comment]
なるほど？

> これは、classを新しくつくる面倒さから直接指定してしまいました…

ちょっと〜？お姉さん？？

> 僕の作業のやりやすさが変わるので分けますね。画面の大きさによっては「やってみよう」が初めから表示されるので、見せ方はすこし考えたほうがよさそうです。

これの検討は新Issueでやりましょ。
